# FROM registry.redhat.io/ansible-automation-platform-25/ee-supported-rhel9:latest
FROM registry.redhat.io/ansible-automation-platform-25/ee-minimal-rhel9:latest

RUN pip3 install 'ansible[azure]'

RUN ansible-galaxy collection install azure.azcollection

COPY requirements.txt /requirements.txt

RUN pip3 install uamqp --no-binary :all:
RUN pip3 install -r /requirements.txt